# Welcome to Jekyll!
#

# Site settings
title: Laid Off Calgary
description: |
  A safe space to process your lay off experience, stay motivated and be connected.
owner: Bianca Sinclair # or company name

first_published: 2016 # if migrating another site, the year of your first publish
email: laidoffcalgary@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #facebook: https://facebook.com/groups/1699692680268327/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

gems:
  - jekyll-seo-tag
# Build settings
markdown: kramdown
#sass:
#  style: compressed
