# Welcome to Jekyll!
#

# Site settings
title: Laid Off Calgary
description: |
  A safe space to process your laid off experience, stay motivated and be connected.
owner: Bianca Sinclair # or company name

first_published: 2016 # if migrating another site, the year of your first publish
email: laidoffcalgary@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://laidoffcalgary.ca" # the base hostname & protocol for your site
safe: true
social:
  #facebook: https://facebook.com/groups/1699692680268327/
  #flickr:
  #instagram:
  #vimeo:
  #reddit:
  #stubleupon:
  #tumblr-square:
  #foursquare:
  #vine:
  #weixin:
  #yelp:
  #tripadvisor:
  #amazon:

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
# Build settings
markdown: kramdown
#sass:
#  style: compressed
google_analytics: UA-97503761-1
